security:
  oauth2:
    client:
      clientId: @keycloak.client.id@
      clientSecret: @keycloak.client.secret@
      accessTokenUri: http://@keycloak.host@:@keycloak.port@/auth/realms/@keycloak.realm@/protocol/openid-connect/token
      userAuthorizationUri: http://@keycloak.host@:@keycloak.port@/auth/realms/@keycloak.realm@/protocol/openid-connect/auth
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri: http://@keycloak.host@:@keycloak.port@/auth/realms/@keycloak.realm@/protocol/openid-connect/userinfo
