---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "springboot-kc-client"
type: Opaque
data:
  clientId: "c3ByaW5nLWJvb3QtZGVtb3M="
  clientSecret: "N2FiNTRjYjMtMTM1Ni00YTY4LTgzZDctYzNjZTliOWVlMmZm"
